# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I am Khanh !
name: KHANH Le
email: lecongkhanh382@gmail.com
location: HCMC, Vietnam
company: Renesas Design Vietnam Co. Ltd.
company_url: #
github_url: https://github.com/khanhcongle
description: This is personnel website of KHANH Le
favicon: favicon.png # Image must be in assets/images

url: #khanhcongle/khanhcongle.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: .disqus.com # TODO: fix this

# Pagination
paginate: 7
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1' # TODO: fix this

# For about.html. Fell free to create your own!
skill_software_keywords: [Python, Java, C++, C, SQLite, MySQL, PL/SQL, Qt, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]