title: Khanh+Note
author: Khanh Le
email: lecongkhanh382@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Personal Note of Khanh Le :")
  
future: true
timezone: Asia/Bangkok

twitter_username: lecongkhanh382@gmail.com
github_username:  lecongkhanh382@gmail.com

sass:
    style: compressed