# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Khafaref
name: Khafast
email: lecongkhanh382@gmail.com
location: HCMC, Vietnam
company: Renesas Design Vietnam Co. Ltd.
company_url: #
github_url: https://github.com/khafast
description: This is a tech reference page built by Khafast
favicon: favicon.png # Image must be in assets/images

url: #khafast/khafast.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: .disqus.com # TODO: fix this

# Pagination
paginate: 7
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1' # TODO: fix this

# For about.html. Fell free to create your own!
skill_software_keywords: [Python, Java, C++, C, SQLite, MySQL] # More: , PL/SQL, Qt, Oracle, Design Patterns
skill_j2ee_keywords: [Spring, JSP] # More: Struct, Hibernet, MyBatis, 
skill_web_keywords: [HTML, CSS, JS, JQuery, AngularJS, Boostrap] #NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Ajax, 
skill_mobile_app_keywords: [] #More Android, iOS,